server:
  port: 8769

spring:
  application:
    name: service-zuul
  zipkin:
    # 服务链路追踪地址
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka/，多个地址用,分隔
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-feign-a
    api-b:
      path: /api-b/**
      serviceId: service-feign-b